name: Print Software Versions

on:
  push:
    branches: [main]

jobs:
  # Виведення версії програмного забезпечення на рівні обробки даних
  PrintClientAndServerSoftwareVersions:
    runs-on: ubuntu-latest
    steps:
      - name: Print Operating System (Client)
        run: uname -a  # Виведення інформації про операційну систему клієнта

      - name: Print Web Framework (Angular)
        run: npx -p @angular/cli ng version  # Виведення версії Angular

      - name: Print Node.js Version (Server)
        run: node --version  # Виведення версії Node.js, використовувану на сервері

  # Виведення версії СУБД на рівні доступу до даних
  PrintDatabaseServerVersion:
    runs-on: ubuntu-latest
    needs: [PrintClientAndServerSoftwareVersions]
    steps:
      - name: Print PostgreSQL Version
        run: psql --version  # Ведення версії PostgreSQL
